name: "Install Poetry Action"
description: "Installs and configures Poetry"
inputs:
  version:
    description: "The Poetry version to install"
    required: false
    default: "1.1.7"
runs:
  using: "composite"
  steps:
    - name: Install and configure Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade virtualenv
        pip install poetry==${{ inputs.version }}
        poetry config virtualenvs.in-project true
      shell: bash